"""Add padre_acudiente role and parent-child relationship

Revision ID: 85b0514d24af
Revises: 0461d6bd6272
Create Date: 2025-08-29 13:47:01.651206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b0514d24af'
down_revision: Union[str, Sequence[str], None] = '0461d6bd6272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('padre_hijos_association',
    sa.Column('padre_id', sa.Integer(), nullable=False),
    sa.Column('hijo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hijo_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('padre_id', 'hijo_id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('admin_general', 'admin_empresa', 'jefe_area', 'profesional_area', 'tecnico_area', 'coordinador', 'profesor', 'alumno', 'padre_acudiente', 'jefe_almacen', 'almacenista', 'jefe_escenarios', name='rolesenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.Enum('admin_general', 'admin_empresa', 'jefe_area', 'profesional_area', 'tecnico_area', 'coordinador', 'profesor', 'alumno', 'padre_acudiente', 'jefe_almacen', 'almacenista', 'jefe_escenarios', name='rolesenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_table('padre_hijos_association')
    # ### end Alembic commands ###
