"""Create gateway-agnostic billing models

Revision ID: 36f3d0a15892
Revises:
Create Date: 2025-08-28 15:02:11.427179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f3d0a15892'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_index(op.f('ix_areas_nombre'), 'areas', ['nombre'], unique=True)
    op.create_table('inquilinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(), nullable=False),
    sa.Column('fecha_suscripcion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('llm_preference', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=True),
    sa.Column('google_api_key', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquilinos_api_key'), 'inquilinos', ['api_key'], unique=True)
    op.create_index(op.f('ix_inquilinos_id'), 'inquilinos', ['id'], unique=False)
    op.create_table('payment_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_gateways_gateway_name'), 'payment_gateways', ['gateway_name'], unique=True)
    op.create_index(op.f('ix_payment_gateways_id'), 'payment_gateways', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('features', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('barrios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barrios_id'), 'barrios', ['id'], unique=False)
    op.create_table('chat_conversaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_mensaje_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversaciones_id'), 'chat_conversaciones', ['id'], unique=False)
    op.create_table('discapacidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discapacidades_id'), 'discapacidades', ['id'], unique=False)
    op.create_table('elementos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elementos_codigo'), 'elementos', ['codigo'], unique=False)
    op.create_index(op.f('ix_elementos_id'), 'elementos', ['id'], unique=False)
    op.create_table('escenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escenarios_id'), 'escenarios', ['id'], unique=False)
    op.create_table('escolaridades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escolaridades_id'), 'escolaridades', ['id'], unique=False)
    op.create_table('gamificacion_acciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('accion_key', sa.String(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamificacion_acciones_id'), 'gamificacion_acciones', ['id'], unique=False)
    op.create_table('gamificacion_medallas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('medalla_key', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('icono_path', sa.String(), nullable=True),
    sa.Column('es_manual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamificacion_medallas_id'), 'gamificacion_medallas', ['id'], unique=False)
    op.create_table('gamificacion_mercado_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('costo_puntos', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamificacion_mercado_items_id'), 'gamificacion_mercado_items', ['id'], unique=False)
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generos_id'), 'generos', ['id'], unique=False)
    op.create_table('grupos_etarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_etarios_id'), 'grupos_etarios', ['id'], unique=False)
    op.create_table('grupos_poblacionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_poblacionales_id'), 'grupos_poblacionales', ['id'], unique=False)
    op.create_table('procesos_formacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre_proceso', sa.String(), nullable=False),
    sa.Column('tipo_proceso', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procesos_formacion_id'), 'procesos_formacion', ['id'], unique=False)
    op.create_table('resguardos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resguardos_id'), 'resguardos', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('generic_customer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquilino_id')
    )
    op.create_index(op.f('ix_subscriptions_generic_customer_id'), 'subscriptions', ['generic_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_documento_id'), 'tipos_documento', ['id'], unique=False)
    op.create_table('tipos_escenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_escenario_id'), 'tipos_escenario', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('admin_general', 'admin_empresa', 'jefe_area', 'coordinador', 'profesor', 'alumno', 'almacenista', 'jefe_almacen', 'jefe_escenarios', 'profesional_cultura', 'profesional_deportes', 'tecnico_cultura', 'tecnico_deportes', 'asistencial_cultura', 'asistencial_deportes', 'instructor_cultura', 'instructor_deportes', name='rolesenum'), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('reporta_a_usuario_id', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('dashboard_layout', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['reporta_a_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=False)
    op.create_table('veredas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veredas_id'), 'veredas', ['id'], unique=False)
    op.create_table('almacenistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('area_almacen', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_almacenistas_id'), 'almacenistas', ['id'], unique=False)
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('documento', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('grupo_etario', sa.String(), nullable=True),
    sa.Column('escolaridad', sa.String(), nullable=True),
    sa.Column('discapacidad', sa.String(), nullable=True),
    sa.Column('grupo_poblacional', sa.String(), nullable=True),
    sa.Column('barrio', sa.String(), nullable=True),
    sa.Column('vereda', sa.String(), nullable=True),
    sa.Column('resguardo', sa.String(), nullable=True),
    sa.Column('zona_geografica', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('puntos_totales', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('mostrar_en_rankings', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_alumnos_documento'), 'alumnos', ['documento'], unique=False)
    op.create_index(op.f('ix_alumnos_id'), 'alumnos', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_actor', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id_actor'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('chat_mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('remitente_usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['chat_conversaciones.id'], ),
    sa.ForeignKeyConstraint(['remitente_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_mensajes_id'), 'chat_mensajes', ['id'], unique=False)
    op.create_table('chat_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['chat_conversaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_participantes_id'), 'chat_participantes', ['id'], unique=False)
    op.create_table('escenario_partes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('escenario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_parte', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['escenario_id'], ['escenarios.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escenario_partes_id'), 'escenario_partes', ['id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('alcance', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lugar', sa.String(), nullable=True),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_table('gamificacion_misiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('puntos_recompensa', sa.Integer(), nullable=True),
    sa.Column('medalla_recompensa_key', sa.String(), nullable=True),
    sa.Column('es_grupal', sa.Boolean(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['medalla_recompensa_key'], ['gamificacion_medallas.medalla_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamificacion_misiones_id'), 'gamificacion_misiones', ['id'], unique=False)
    op.create_table('jefes_almacen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_jefes_almacen_id'), 'jefes_almacen', ['id'], unique=False)
    op.create_table('jefes_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_jefes_area_id'), 'jefes_area', ['id'], unique=False)
    op.create_table('jefes_escenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_jefes_escenarios_id'), 'jefes_escenarios', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('gateway_name', sa.String(), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gateway_name'], ['payment_gateways.gateway_name'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_gateway_transaction_id'), 'payments', ['gateway_transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('plan_curricular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre_plan', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos_formacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_curricular_id'), 'plan_curricular', ['id'], unique=False)
    op.create_table('profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_profesores_id'), 'profesores', ['id'], unique=False)
    op.create_table('usuario_areas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'area_id')
    )
    op.create_table('clases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre_clase', sa.String(), nullable=True),
    sa.Column('proceso_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_inicio', sa.String(), nullable=True),
    sa.Column('hora_fin', sa.String(), nullable=True),
    sa.Column('escenario_id', sa.Integer(), nullable=True),
    sa.Column('espacio', sa.String(), nullable=True),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.Column('novedad', sa.Text(), nullable=True),
    sa.Column('area', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['escenario_id'], ['escenarios.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['profesores.id'], ),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos_formacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clases_id'), 'clases', ['id'], unique=False)
    op.create_table('coordinadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('jefe_area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['jefe_area_id'], ['jefes_area.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_coordinadores_id'), 'coordinadores', ['id'], unique=False)
    op.create_table('evento_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_participacion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_participantes_id'), 'evento_participantes', ['id'], unique=False)
    op.create_table('gamificacion_compras_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('costo_en_puntos', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['gamificacion_mercado_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamificacion_compras_log_id'), 'gamificacion_compras_log', ['id'], unique=False)
    op.create_table('gamificacion_medallas_obtenidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('medalla_key', sa.String(), nullable=False),
    sa.Column('fecha_obtencion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamificacion_medallas_obtenidas_id'), 'gamificacion_medallas_obtenidas', ['id'], unique=False)
    op.create_table('gamificacion_misiones_progreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mision_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('fecha_completada', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['mision_id'], ['gamificacion_misiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamificacion_misiones_progreso_id'), 'gamificacion_misiones_progreso', ['id'], unique=False)
    op.create_table('gamificacion_puntos_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('accion_key', sa.String(), nullable=False),
    sa.Column('puntos_ganados', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamificacion_puntos_log_id'), 'gamificacion_puntos_log', ['id'], unique=False)
    op.create_table('plan_curricular_temas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_curricular_id', sa.Integer(), nullable=False),
    sa.Column('nombre_tema', sa.String(), nullable=False),
    sa.Column('descripcion_tema', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_curricular_id'], ['plan_curricular.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_curricular_temas_id'), 'plan_curricular_temas', ['id'], unique=False)
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('elemento_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('almacenista_id', sa.Integer(), nullable=True),
    sa.Column('fecha_prestamo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones_prestamo', sa.Text(), nullable=True),
    sa.Column('foto_prestamo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones_entrega', sa.Text(), nullable=True),
    sa.Column('foto_entrega', sa.String(), nullable=True),
    sa.Column('estado_entrega', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['almacenista_id'], ['almacenistas.id'], ),
    sa.ForeignKeyConstraint(['elemento_id'], ['elementos.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['profesores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prestamos_id'), 'prestamos', ['id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('escenario_parte_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_reserva', sa.Integer(), nullable=False),
    sa.Column('proposito', sa.String(), nullable=True),
    sa.Column('descripcion_proposito', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['escenario_parte_id'], ['escenario_partes.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id_reserva'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('clase_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidencia_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['clase_id'], ['clases.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_id'), 'asistencias', ['id'], unique=False)
    op.create_table('contenido_curricular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('tipo_contenido', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('ruta_archivo_o_url', sa.String(), nullable=False),
    sa.Column('subido_por_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subido_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['plan_curricular_temas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contenido_curricular_id'), 'contenido_curricular', ['id'], unique=False)
    op.create_table('foros_clases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('nombre_foro', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['clases.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clase_id')
    )
    op.create_index(op.f('ix_foros_clases_id'), 'foros_clases', ['id'], unique=False)
    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('clase_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nivel_formacion', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['clase_id'], ['clases.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscripciones_id'), 'inscripciones', ['id'], unique=False)
    op.create_table('planificador_clases_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['clases.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['plan_curricular_temas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planificador_clases_eventos_id'), 'planificador_clases_eventos', ['id'], unique=False)
    op.create_table('progreso_alumno_tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_usuario_id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('evaluacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['plan_curricular_temas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progreso_alumno_tema_id'), 'progreso_alumno_tema', ['id'], unique=False)
    op.create_table('foros_hilos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foro_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['foro_id'], ['foros_clases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foros_hilos_id'), 'foros_hilos', ['id'], unique=False)
    op.create_table('foros_publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hilo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responde_a_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hilo_id'], ['foros_hilos.id'], ),
    sa.ForeignKeyConstraint(['responde_a_id'], ['foros_publicaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foros_publicaciones_id'), 'foros_publicaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foros_publicaciones_id'), table_name='foros_publicaciones')
    op.drop_table('foros_publicaciones')
    op.drop_index(op.f('ix_foros_hilos_id'), table_name='foros_hilos')
    op.drop_table('foros_hilos')
    op.drop_index(op.f('ix_progreso_alumno_tema_id'), table_name='progreso_alumno_tema')
    op.drop_table('progreso_alumno_tema')
    op.drop_index(op.f('ix_planificador_clases_eventos_id'), table_name='planificador_clases_eventos')
    op.drop_table('planificador_clases_eventos')
    op.drop_index(op.f('ix_inscripciones_id'), table_name='inscripciones')
    op.drop_table('inscripciones')
    op.drop_index(op.f('ix_foros_clases_id'), table_name='foros_clases')
    op.drop_table('foros_clases')
    op.drop_index(op.f('ix_contenido_curricular_id'), table_name='contenido_curricular')
    op.drop_table('contenido_curricular')
    op.drop_index(op.f('ix_asistencias_id'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_prestamos_id'), table_name='prestamos')
    op.drop_table('prestamos')
    op.drop_index(op.f('ix_plan_curricular_temas_id'), table_name='plan_curricular_temas')
    op.drop_table('plan_curricular_temas')
    op.drop_index(op.f('ix_gamificacion_puntos_log_id'), table_name='gamificacion_puntos_log')
    op.drop_table('gamificacion_puntos_log')
    op.drop_index(op.f('ix_gamificacion_misiones_progreso_id'), table_name='gamificacion_misiones_progreso')
    op.drop_table('gamificacion_misiones_progreso')
    op.drop_index(op.f('ix_gamificacion_medallas_obtenidas_id'), table_name='gamificacion_medallas_obtenidas')
    op.drop_table('gamificacion_medallas_obtenidas')
    op.drop_index(op.f('ix_gamificacion_compras_log_id'), table_name='gamificacion_compras_log')
    op.drop_table('gamificacion_compras_log')
    op.drop_index(op.f('ix_evento_participantes_id'), table_name='evento_participantes')
    op.drop_table('evento_participantes')
    op.drop_index(op.f('ix_coordinadores_id'), table_name='coordinadores')
    op.drop_table('coordinadores')
    op.drop_index(op.f('ix_clases_id'), table_name='clases')
    op.drop_table('clases')
    op.drop_table('usuario_areas')
    op.drop_index(op.f('ix_profesores_id'), table_name='profesores')
    op.drop_table('profesores')
    op.drop_index(op.f('ix_plan_curricular_id'), table_name='plan_curricular')
    op.drop_table('plan_curricular')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_transaction_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_jefes_escenarios_id'), table_name='jefes_escenarios')
    op.drop_table('jefes_escenarios')
    op.drop_index(op.f('ix_jefes_area_id'), table_name='jefes_area')
    op.drop_table('jefes_area')
    op.drop_index(op.f('ix_jefes_almacen_id'), table_name='jefes_almacen')
    op.drop_table('jefes_almacen')
    op.drop_index(op.f('ix_gamificacion_misiones_id'), table_name='gamificacion_misiones')
    op.drop_table('gamificacion_misiones')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_escenario_partes_id'), table_name='escenario_partes')
    op.drop_table('escenario_partes')
    op.drop_index(op.f('ix_chat_participantes_id'), table_name='chat_participantes')
    op.drop_table('chat_participantes')
    op.drop_index(op.f('ix_chat_mensajes_id'), table_name='chat_mensajes')
    op.drop_table('chat_mensajes')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alumnos_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_documento'), table_name='alumnos')
    op.drop_table('alumnos')
    op.drop_index(op.f('ix_almacenistas_id'), table_name='almacenistas')
    op.drop_table('almacenistas')
    op.drop_index(op.f('ix_veredas_id'), table_name='veredas')
    op.drop_table('veredas')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_escenario_id'), table_name='tipos_escenario')
    op.drop_table('tipos_escenario')
    op.drop_index(op.f('ix_tipos_documento_id'), table_name='tipos_documento')
    op.drop_table('tipos_documento')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_generic_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_resguardos_id'), table_name='resguardos')
    op.drop_table('resguardos')
    op.drop_index(op.f('ix_procesos_formacion_id'), table_name='procesos_formacion')
    op.drop_table('procesos_formacion')
    op.drop_index(op.f('ix_grupos_poblacionales_id'), table_name='grupos_poblacionales')
    op.drop_table('grupos_poblacionales')
    op.drop_index(op.f('ix_grupos_etarios_id'), table_name='grupos_etarios')
    op.drop_table('grupos_etarios')
    op.drop_index(op.f('ix_generos_id'), table_name='generos')
    op.drop_table('generos')
    op.drop_index(op.f('ix_gamificacion_mercado_items_id'), table_name='gamificacion_mercado_items')
    op.drop_table('gamificacion_mercado_items')
    op.drop_index(op.f('ix_gamificacion_medallas_id'), table_name='gamificacion_medallas')
    op.drop_table('gamificacion_medallas')
    op.drop_index(op.f('ix_gamificacion_acciones_id'), table_name='gamificacion_acciones')
    op.drop_table('gamificacion_acciones')
    op.drop_index(op.f('ix_escolaridades_id'), table_name='escolaridades')
    op.drop_table('escolaridades')
    op.drop_index(op.f('ix_escenarios_id'), table_name='escenarios')
    op.drop_table('escenarios')
    op.drop_index(op.f('ix_elementos_id'), table_name='elementos')
    op.drop_index(op.f('ix_elementos_codigo'), table_name='elementos')
    op.drop_table('elementos')
    op.drop_index(op.f('ix_discapacidades_id'), table_name='discapacidades')
    op.drop_table('discapacidades')
    op.drop_index(op.f('ix_chat_conversaciones_id'), table_name='chat_conversaciones')
    op.drop_table('chat_conversaciones')
    op.drop_index(op.f('ix_barrios_id'), table_name='barrios')
    op.drop_table('barrios')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_payment_gateways_id'), table_name='payment_gateways')
    op.drop_index(op.f('ix_payment_gateways_gateway_name'), table_name='payment_gateways')
    op.drop_table('payment_gateways')
    op.drop_index(op.f('ix_inquilinos_id'), table_name='inquilinos')
    op.drop_index(op.f('ix_inquilinos_api_key'), table_name='inquilinos')
    op.drop_table('inquilinos')
    op.drop_index(op.f('ix_areas_nombre'), table_name='areas')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
